### ISSUE TITLE
`\topskip0pt` causes unexpected extra blank pages between chapters

### ISSUE THREAD

**Issue by FTHuld** [uis-no/thesis-template#2]
`\topskip` seems to have some very weird behaviour. When `\topskip0pt` is present (as default in `quote.tex` and the `\declaration`) in the `\frontmatter`, an extra two (sometimes 3) blank pages are inserted between the chapters in the main document.

Luckily there are only two default instances of `topskip` in the template,* and removing them doesn't seem to make a noticeable difference to the presentation (apart from removing those extra pages).

\* one on line 3 in `frontmatter/quote.tex`; and one on line 427 in `uis-thesis.sty`

I'm posting this here mainly because it took me two days to find it, and I want to share in case others have the same issue.

**Comment by meling** [comment]
Thanks for reporting this. I've fixed the problem over at [uis-no/uis-thesis](https://github.com/uis-no/uis-thesis). This repo contains an older thesis template no longer being maintained AFAIK.

**Comment by FTHuld** [comment]
Thanks!

Might be worth deprecating the repo if it's no longer being maintained. That avoids having to field issues arriving from the older template.
